import type { CatalogItem } from './items'

// 실제 PNG 에셋이 제작된 아이템만 등록한다. (목데이터 금지)
export const ITEM_CATALOG: CatalogItem[] = [
  // top
  {
    id: 'top_001',
    category: 'top',
    subCategory: '나시',
    name: '일반 나시',
    color: '#24231F',
    imagePath: 'assets/avatar/top/top_001_black.png',
    styleTags: ['minimal', 'chic'],
  },
  {
    id: 'top_002',
    category: 'top',
    subCategory: '티셔츠',
    name: '브이넥 무지 티',
    color: '#F5F5F5',
    imagePath: 'assets/avatar/top/top_002_white.png',
    styleTags: ['casual', 'minimal'],
  },
  {
    id: 'top_003',
    category: 'top',
    subCategory: '나시',
    name: '크롭 나시',
    color: '#1E2520',
    imagePath: 'assets/avatar/top/top_003_black_crop.png',
    styleTags: ['street', 'chic'],
  },
  {
    id: 'top_005',
    category: 'top',
    subCategory: '맨투맨',
    name: '화이트 맨투맨',
    color: '#EFEDE7',
    imagePath: 'assets/avatar/top/top_005_white_sweatshirt.png',
    styleTags: ['casual', 'minimal'],
  },
  {
    id: 'top_006',
    category: 'top',
    subCategory: '셔츠',
    name: '화이트 셔츠',
    color: '#FAF8F0',
    imagePath: 'assets/avatar/top/top_006_white_shirt.png',
    styleTags: ['formal', 'minimal'],
  },

  // outer
  {
    id: 'outer_001',
    category: 'outer',
    subCategory: '가디건',
    name: '크림 가디건',
    color: '#F4DDB9',
    imagePath: 'assets/avatar/outer/outer_001_cream_cardigan.png',
    styleTags: ['casual', 'feminine'],
  },

  // dress
  {
    id: 'dress_001',
    category: 'dress',
    subCategory: '미니 원피스',
    name: '크림 리본 원피스',
    color: '#F7E8C8',
    imagePath: 'assets/avatar/dress/dress_001_cream_onepiece.png',
    styleTags: ['feminine', 'vintage'],
  },

  // bottom
  {
    id: 'bottom_009',
    category: 'bottom',
    subCategory: '스커트',
    name: '청색 치마',
    color: '#9CB8CC',
    imagePath: 'assets/avatar/bottom/bottom_009_blue.png',
    styleTags: ['casual', 'feminine'],
  },
  {
    id: 'bottom_010',
    category: 'bottom',
    subCategory: '팬츠',
    name: '청 와이드 팬츠',
    color: '#6B8CAE',
    imagePath: 'assets/avatar/bottom/bottom_010_blue.png',
    styleTags: ['casual', 'street'],
  },
  {
    id: 'bottom_011',
    category: 'bottom',
    subCategory: '팬츠',
    name: '트레이닝 팬츠',
    color: '#C8C6CA',
    imagePath: 'assets/avatar/bottom/bottom_011_gray.png',
    styleTags: ['casual', 'sporty'],
  },
  {
    id: 'bottom_012',
    category: 'bottom',
    subCategory: '스커트',
    name: '크림 롱스커트',
    color: '#F3E1C3',
    imagePath: 'assets/avatar/bottom/bottom_012_cream_long_skirt.png',
    styleTags: ['feminine', 'vintage'],
  },
  {
    id: 'bottom_013',
    category: 'bottom',
    subCategory: '팬츠',
    name: '블랙 슬랙스',
    color: '#202020',
    imagePath: 'assets/avatar/bottom/bottom_013_black_slacks.png',
    styleTags: ['formal', 'chic'],
  },
  {
    id: 'bottom_014',
    category: 'bottom',
    subCategory: '쇼츠',
    name: '데님 쇼츠',
    color: '#233B5C',
    imagePath: 'assets/avatar/bottom/bottom_014_blue_shorts.png',
    styleTags: ['casual', 'street'],
  },

  // shoes
  {
    id: 'shoes_001',
    category: 'shoes',
    subCategory: '스니커즈',
    name: '스니커즈',
    color: '#F0F0F0',
    imagePath: 'assets/avatar/shoes/shoes_001_white.png',
    styleTags: ['casual', 'sporty'],
  },
  {
    id: 'shoes_002',
    category: 'shoes',
    subCategory: '부츠',
    name: '부츠',
    color: '#1C1C1C',
    imagePath: 'assets/avatar/shoes/shoes_002_black.png',
    styleTags: ['street', 'chic'],
  },
  {
    id: 'shoes_007',
    category: 'shoes',
    subCategory: '구두',
    name: '구두',
    color: '#111111',
    imagePath: 'assets/avatar/shoes/shoes_007_black.png',
    styleTags: ['formal', 'chic'],
  },

  // hair
  {
    id: 'hair_001',
    category: 'hair',
    subCategory: '전체',
    name: '단발머리',
    color: '#5A4036',
    imagePath: 'assets/avatar/hair/hair_001_brown.png',
    styleTags: ['casual', 'feminine'],
  },
  {
    id: 'hair_002',
    category: 'hair',
    subCategory: '전체',
    name: '포니테일',
    color: '#70482F',
    imagePath: 'assets/avatar/hair/hair_002_brown.png',
    styleTags: ['casual', 'sporty'],
  },

  // accessory
  {
    id: 'accessory_001',
    category: 'accessory',
    subCategory: '안경',
    name: '원형 안경',
    color: '#8C5B52',
    imagePath: 'assets/avatar/accessory/accessory_001_glasses.png',
    styleTags: ['minimal', 'chic'],
  },
  {
    id: 'accessory_002',
    category: 'accessory',
    subCategory: '니삭스',
    name: '화이트 니삭스',
    color: '#F5F5F5',
    imagePath: 'assets/avatar/accessory/accessory_002_knee_socks.png',
    styleTags: ['feminine', 'preppy'],
  },
  {
    id: 'accessory_003',
    category: 'accessory',
    subCategory: '목걸이',
    name: '블루 펜던트 목걸이',
    color: '#1F5D99',
    imagePath: 'assets/avatar/accessory/accessory_003_necklace.png',
    styleTags: ['minimal', 'chic'],
  },
  {
    id: 'accessory_004',
    category: 'accessory',
    subCategory: '시계',
    name: '메탈 시계',
    color: '#4F5873',
    imagePath: 'assets/avatar/accessory/accessory_004_watch.png',
    styleTags: ['minimal', 'chic'],
  },
  {
    id: 'accessory_005',
    category: 'accessory',
    subCategory: '모자',
    name: '크림 볼캡',
    color: '#F2D7A9',
    imagePath: 'assets/avatar/accessory/accessory_005_cap.png',
    styleTags: ['casual', 'sporty'],
  },
]
