import type { CatalogItem } from './items'

// 실제 PNG 에셋이 제작된 아이템만 등록한다. (목데이터 금지)
export const ITEM_CATALOG: CatalogItem[] = [
  // top
  {
    id: 'top_001',
    category: 'top',
    subCategory: '나시',
    name: '일반 나시',
    color: '#24231F',
    imagePath: 'assets/avatar/top/top_001_black.png',
    styleTags: ['minimal', 'chic'],
  },
  {
    id: 'top_002',
    category: 'top',
    subCategory: '티셔츠',
    name: '브이넥 무지 티',
    color: '#F5F5F5',
    imagePath: 'assets/avatar/top/top_002_white.png',
    styleTags: ['casual', 'minimal'],
  },
  {
    id: 'top_003',
    category: 'top',
    subCategory: '나시',
    name: '크롭 나시',
    color: '#1E2520',
    imagePath: 'assets/avatar/top/top_003_black_crop.png',
    styleTags: ['street', 'chic'],
  },
  {
    id: 'top_005',
    category: 'top',
    subCategory: '맨투맨',
    name: '맨투맨',
    color: '#EFEDE7',
    imagePath: 'assets/avatar/top/top_005_white_sweatshirt.png',
    styleTags: ['casual', 'minimal'],
  },
  {
    id: 'top_006',
    category: 'top',
    subCategory: '셔츠',
    name: '셔츠',
    color: '#FAF8F0',
    imagePath: 'assets/avatar/top/top_006_white_shirt.png',
    styleTags: ['formal', 'minimal'],
  },
  {
    id: 'top_007',
    category: 'top',
    subCategory: '티셔츠',
    name: '기본 티셔츠',
    color: '#C9C5C3',
    imagePath: 'assets/avatar/top/top_007_gray_basic_tshirt.png',
    styleTags: ['casual', 'minimal'],
  },
  {
    id: 'top_008',
    category: 'top',
    subCategory: '블라우스',
    name: '블라우스',
    color: '#242225',
    imagePath: 'assets/avatar/top/top_008_black_blouse.png',
    styleTags: ['feminine', 'chic'],
  },
  {
    id: 'top_009',
    category: 'top',
    subCategory: '티셔츠',
    name: '스트라이프 티셔츠',
    color: '#31476E',
    imagePath: 'assets/avatar/top/top_009_cream_navy_striped_tshirt.png',
    styleTags: ['casual', 'preppy'],
  },

  // outer
  {
    id: 'outer_001',
    category: 'outer',
    subCategory: '가디건',
    name: '가디건',
    color: '#F4DDB9',
    imagePath: 'assets/avatar/outer/outer_001_cream_cardigan.png',
    styleTags: ['casual', 'feminine'],
  },
  {
    id: 'outer_002',
    category: 'outer',
    subCategory: '후드집업',
    name: '후드집업',
    color: '#E8E0D5',
    imagePath: 'assets/avatar/outer/outer_002_cream_hoodie_zipup.png',
    styleTags: ['casual', 'sporty'],
  },

  // dress
  {
    id: 'dress_001',
    category: 'dress',
    subCategory: '미니 원피스',
    name: '리본 원피스',
    color: '#F7E8C8',
    imagePath: 'assets/avatar/dress/dress_001_cream_onepiece.png',
    styleTags: ['feminine', 'vintage'],
  },
  {
    id: 'dress_002',
    category: 'dress',
    subCategory: '롱 원피스',
    name: '롱원피스',
    color: '#F5E9D7',
    imagePath: 'assets/avatar/dress/dress_002_cream_long_onepiece.png',
    styleTags: ['feminine', 'vintage'],
  },

  // bottom
  {
    id: 'bottom_009',
    category: 'bottom',
    subCategory: '스커트',
    name: '치마',
    color: '#9CB8CC',
    imagePath: 'assets/avatar/bottom/bottom_009_blue.png',
    styleTags: ['casual', 'feminine'],
  },
  {
    id: 'bottom_010',
    category: 'bottom',
    subCategory: '팬츠',
    name: '와이드 팬츠',
    color: '#6B8CAE',
    imagePath: 'assets/avatar/bottom/bottom_010_blue.png',
    styleTags: ['casual', 'street'],
  },
  {
    id: 'bottom_011',
    category: 'bottom',
    subCategory: '팬츠',
    name: '트레이닝 팬츠',
    color: '#C8C6CA',
    imagePath: 'assets/avatar/bottom/bottom_011_gray.png',
    styleTags: ['casual', 'sporty'],
  },
  {
    id: 'bottom_012',
    category: 'bottom',
    subCategory: '스커트',
    name: '크림 롱스커트',
    color: '#F3E1C3',
    imagePath: 'assets/avatar/bottom/bottom_012_cream_long_skirt.png',
    styleTags: ['feminine', 'vintage'],
  },
  {
    id: 'bottom_013',
    category: 'bottom',
    subCategory: '팬츠',
    name: '슬랙스',
    color: '#202020',
    imagePath: 'assets/avatar/bottom/bottom_013_black_slacks.png',
    styleTags: ['formal', 'chic'],
  },
  {
    id: 'bottom_014',
    category: 'bottom',
    subCategory: '쇼츠',
    name: '데님 쇼츠',
    color: '#233B5C',
    imagePath: 'assets/avatar/bottom/bottom_014_blue_shorts.png',
    styleTags: ['casual', 'street'],
  },
  {
    id: 'bottom_015',
    category: 'bottom',
    subCategory: '스커트',
    name: 'H라인 스커트',
    color: '#242424',
    imagePath: 'assets/avatar/bottom/bottom_015_black_h_line_skirt.png',
    styleTags: ['minimal', 'chic'],
  },
  {
    id: 'bottom_016',
    category: 'bottom',
    subCategory: '스커트',
    name: '플리츠 스커트',
    color: '#A3A3AA',
    imagePath: 'assets/avatar/bottom/bottom_016_gray_pleated_skirt.png',
    styleTags: ['feminine', 'preppy'],
  },

  // shoes
  {
    id: 'shoes_001',
    category: 'shoes',
    subCategory: '스니커즈',
    name: '스니커즈',
    color: '#F0F0F0',
    imagePath: 'assets/avatar/shoes/shoes_001_white.png',
    styleTags: ['casual', 'sporty'],
  },
  {
    id: 'shoes_002',
    category: 'shoes',
    subCategory: '부츠',
    name: '부츠',
    color: '#1C1C1C',
    imagePath: 'assets/avatar/shoes/shoes_002_black.png',
    styleTags: ['street', 'chic'],
  },
  {
    id: 'shoes_007',
    category: 'shoes',
    subCategory: '구두',
    name: '구두',
    color: '#111111',
    imagePath: 'assets/avatar/shoes/shoes_007_black.png',
    styleTags: ['formal', 'chic'],
  },
  {
    id: 'shoes_008',
    category: 'shoes',
    subCategory: '로퍼',
    name: '로퍼',
    color: '#1F1F20',
    imagePath: 'assets/avatar/shoes/shoes_008_black_loafer.png',
    styleTags: ['formal', 'preppy'],
  },

  // hair
  {
    id: 'hair_001',
    category: 'hair',
    subCategory: '전체',
    name: '단발머리',
    color: '#5A4036',
    imagePath: 'assets/avatar/hair/hair_001_brown.png',
    styleTags: ['casual', 'feminine'],
  },
  {
    id: 'hair_002',
    category: 'hair',
    subCategory: '전체',
    name: '포니테일',
    color: '#70482F',
    imagePath: 'assets/avatar/hair/hair_002_brown.png',
    styleTags: ['casual', 'sporty'],
  },
  {
    id: 'hair_003',
    category: 'hair',
    subCategory: '전체',
    name: '숏컷',
    color: '#885C4A',
    imagePath: 'assets/avatar/hair/hair_003_brown_short_cut.png',
    styleTags: ['casual', 'minimal'],
  },
  {
    id: 'hair_004',
    category: 'hair',
    subCategory: '전체',
    name: '반묶음',
    color: '#A27666',
    imagePath: 'assets/avatar/hair/hair_004_brown_half_up.png',
    styleTags: ['feminine', 'casual'],
  },
  {
    id: 'hair_005',
    category: 'hair',
    subCategory: '전체',
    name: '긴 생머리',
    color: '#4A3023',
    imagePath: 'assets/avatar/hair/hair_005_dark_brown_long_straight.png',
    styleTags: ['feminine', 'minimal'],
  },
  {
    id: 'hair_006',
    category: 'hair',
    subCategory: '전체',
    name: '숏단발',
    color: '#584238',
    imagePath: 'assets/avatar/hair/hair_006_dark_brown_short_bob.png',
    styleTags: ['casual', 'minimal'],
  },

  // accessory
  {
    id: 'accessory_001',
    category: 'accessory',
    subCategory: '안경',
    name: '원형 안경',
    color: '#8C5B52',
    imagePath: 'assets/avatar/accessory/accessory_001_glasses.png',
    styleTags: ['minimal', 'chic'],
  },
  {
    id: 'accessory_002',
    category: 'accessory',
    subCategory: '니삭스',
    name: '니삭스',
    color: '#F5F5F5',
    imagePath: 'assets/avatar/accessory/accessory_002_knee_socks.png',
    styleTags: ['feminine', 'preppy'],
  },
  {
    id: 'accessory_003',
    category: 'accessory',
    subCategory: '목걸이',
    name: '펜던트 목걸이',
    color: '#1F5D99',
    imagePath: 'assets/avatar/accessory/accessory_003_necklace.png',
    styleTags: ['minimal', 'chic'],
  },
  {
    id: 'accessory_004',
    category: 'accessory',
    subCategory: '시계',
    name: '메탈 시계',
    color: '#4F5873',
    imagePath: 'assets/avatar/accessory/accessory_004_watch.png',
    styleTags: ['minimal', 'chic'],
  },
  {
    id: 'accessory_006',
    category: 'accessory',
    subCategory: '가방',
    name: '숄더 백',
    color: '#9B5A3B',
    imagePath: 'assets/avatar/accessory/accessory_006_brown_shoulder_bag.png',
    styleTags: ['casual', 'chic'],
  },
  {
    id: 'accessory_007',
    category: 'accessory',
    subCategory: '선글라스',
    name: '선글라스',
    color: '#1F1F20',
    imagePath: 'assets/avatar/accessory/accessory_007_black_sunglasses.png',
    styleTags: ['minimal', 'chic'],
  },
]
